#!/bin/bash

DEBUG=OFF

# Color for output

red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`

CC=56    # BEL Country_Code 56

SEDDIR="$(dirname $0)/sed"
AWKDIR="$(dirname $0)/awk"

# List of download URL

[ "$DEBUG" = "ON" ] && TEMP="/tmp/rki" || TEMP="/tmp/rki-$(date '+%F')"
[ ! -d  "${TEMP}" ] && mkdir "${TEMP}"

URL="https://epistat.sciensano.be/Data/COVID19BE_MORT.csv"
DEST="$TEMP/bel.csv"
CSV="$TEMP/bel"

function download {

# Download table

[ ! -e "$DEST" ] && curl --output "$DEST" --url "$URL"

# if [ $? -eq 0 ] 
# then
#  ssconvert  -S --export-type=Gnumeric_stf:stf_csv "$DEST" "${CSV}%n.csv"
# fi

}

function import {

    # BEL Country_Code 56

    ( echo 'CountryCode,Sex,Altersgruppe,Bis,Todesfall'
      sed --file "$SEDDIR/$CC.sed"  < "${CSV}.csv" \
    | awk -F ',' -e 'BEGIN { CC='$CC';}' -f "$AWKDIR/$CC.awk"  
    ) > "../data/CoViD19Deaths/$CC.csv"
    
}

download
import
