#!/bin/bash

# Import CoViD-19 deaths into database

DATA=$(dirname $0)

pushd $DATA/../data/CoViD19Deaths/ > /dev/null 

echo '-- Import Deaths by country and age'
echo '-- ' $(date +%F)
echo 'USE COVID19;'


for CCF in *.csv
do
CC=$(echo $CCF | sed 's#\.csv##')

echo -e "-- $CCF"
echo "delete from WorldDeaths where CountryCode = $CC;"

 cat $CCF \
| sed '1d' \
| tr ',' ';' \
| tr -d '.' \
| awk -F ';' '{ for (i=$3;i<=$4;i++) { print ("insert into WorldDeaths values (" $1 ",\"" $2 "\"," i "," $5/($4-$3+1) ");" )}}'

done

popd > /dev/null
