#!/bin/bash

# Get times series for US death and confirmed cases

TARGET="/home/thomas/git/R-Example/data/"
TEMP=$(mktemp -d)

GIT="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series"
TYPES=(confirmed deaths)
TABLES=(jhucases jhudeaths)

function Download {

    for SUBSET in US global
    do
        for DATA in confirmed deaths
        do
            wget -O "${TEMP}/${SUBSET}-${DATA}.csv" \
                "$GIT/time_series_covid19_${DATA}_${SUBSET}.csv"

        done

    done
}

function US {

    OFFSET=(11 12)

    for i in 0 1
    do
        (   echo UID,day,count
            cat "$TEMP/US-${DATA}.csv" \
            | sed -n  '1d; s#,"[^"]*"##; s#\(,[^,]*\)\{'${OFFSET[$i]}'\}##; h; :a; x ; s#^\([^,]*\),\([0-9]*\).*#\1,\2#p; g; s#^\([^,]*\),\([0-9]*\)#\1#; t a;' \
            | awk -F ',' 'BEGIN { i=0;UID==0} {if ($1 == UID) {i=i+1;print ($1 "," i "," $2);} else { UID=$1;i=1; print($1 "," 0 "," 0); print ( $1 "," i"," $2 );}}'
        ) > "US-${TYPES[$i]}.csv"
    done
    sudo rm -f /tmp/us.csv us.csv 
    mysql --user=rscript --password=rscript -b < ~/git/R-Example/SQL/US_cases.sql
    sudo mv /tmp/us.csv .

}

function global_data {

(
cat <<EOF
USE COVID19;

DROP TABLE IF EXISTS jhucountry;

CREATE TABLE jhucountry ( 
      cid BIGINT primary key
    , Province_State CHAR(255)
    , Country_Region CHAR(255)
    , Latitude DOUBLE
    , Longitude DOUBLE
    , INDEX (cid)
    );
SET autocommit=0;
LOCK TABLE jhucountry WRITE;
EOF
# Countries
cat "${TEMP}/global-confirmed.csv" \
| sed '1d; s#"\([^"]*\), *\([^"]*\)"#\2/\1#g; s#^\(\([^,]*,\)\{4\}\).*#\1#' \
| awk -F ',' 'BEGIN {i=1;} { print("INSERT INTO jhucountry VALUES ( " i ",\"" $1 "\",\"" $2 "\"," $3 ","$4 ");"); i=i+1; }'
cat <<EOF
COMMIT;
UNLOCK TABLES;
EOF
) | mysql --user=rscript --password=rscript

for i in 0 1
do
(
cat <<EOF
USE COVID19;
DROP TABLE IF EXISTS ${TABLES[$i]};

CREATE TABLE ${TABLES[$i]} ( cid BIGINT , reported DATE, count BIGINT, INDEX (cid, reported));

SET autocommit=0;
LOCK TABLE ${TABLES[$i]} WRITE;
EOF
cat "${TEMP}/global-${TYPES[$i]}.csv" \
| sed '1d; s#"\([^"]*\), *\([^"]*\)"#\2/\1#g;' \
| sed 's#^\([^,]*\),\([^,]*\),\([^,]*,\)\{2\}#-\n#; s#\([^,]*\),#\1\n#g' \
| sed 's#/$##' \
| awk 'BEGIN {i=-1;j=0;} { if ($1=="-") { i=0; j=j+1; v=0} else { v=$1 };print("INSERT INTO '${TABLES[$i]}' VALUES (" j ", ADDDATE(\"2020-01-21\"," i ")," v ");") ; i=i+1; }'
cat <<EOF
COMMIT;
UNLOCK TABLES;
EOF
) | mysql --user=rscript --password=rscript

done

(
cat <<EOF
USE COVID19;

DROP TABLE IF EXISTS jhu;

CREATE TABLE jhu as 
SELECT 
      a.cid as cid
    , b.reported as reported
    , b.count as cases
    , c.count as deaths
FROM jhucountry as a 
INNER JOIN jhucases as b 
    ON b.cid=a.cid 
INNER JOIN jhudeaths as c 
    ON 
        a.cid = c.cid 
        and b.reported = c.reported ;
ALTER TABLE jhu ADD INDEX (cid, reported);

EOF
) | mysql --user=rscript --password=rscript

}

pushd ${TARGET}

Download
global_data
US
 
popd

pushd ~/git/R-Example/COVID19
 
for r in *.r
do
	echo -e "--- $r ---"
 	Rscript $r
done
popd

pushd ~/git/R-Example/JHU
 
for r in *.r
do
	echo -e "--- $r ---"
 	Rscript $r
done
popd
