#!/bin/bash

# Get times series for US death and confirmed cases

TARGET="/home/thomas/git/R-Example/data/"
TEMP=$(mktemp -d)

GIT="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series"
TYPES=(confirmed deaths)

function Download {

    for SUBSET in US global
    do
        for DATA in confirmed deaths
        do
            wget -O "${TEMP}/${SUBSET}-${DATA}.csv" \
                "$GIT/time_series_covid19_${DATA}_${SUBSET}.csv"

        done

    done
}

function US {

    OFFSET=(11 12)

    for i in 0 1
    do
        (   echo UID,day,count
            cat "$TEMP/US-${TYPES[$i]}.csv" \
            | sed -n  '1d; s#,"[^"]*"##; s#\(,[^,]*\)\{'${OFFSET[$i]}'\}##; h; :a; x ; s#^\([^,]*\),\([0-9]*\).*#\1,\2#p; g; s#^\([^,]*\),\([0-9]*\)#\1#; t a;' \
            | awk -F ',' 'BEGIN { i=0;UID==0} {if ($1 == UID) {i=i+1;print ($1 "," i "," $2);} else { UID=$1;i=1; print($1 "," 0 "," 0); print ( $1 "," i"," $2 );}}'
        ) > "US-${TYPES[$i]}.csv"
    done
    sudo rm -f /tmp/us.csv us.csv 
    mysql --user=rscript --password=rscript -b < ~/git/R-Example/SQL/US_cases.sql
    sudo mv /tmp/us.csv .

}

function Germany {

    for DATA in confirmed deaths
    do
        ( grep Germany "$TEMP/global-${DATA}.csv" \
        | tr ',' '\n' \
        | sed '1,4 d' \
        ) > "$TEMP/Germany-${DATA}.csv"
    done
    ( 
        echo -e "Date,Kw,WTag,Cases,Deaths\n0,4,0,0,0\n1,4,1,0,0"
        paste "$TEMP/Germany-${TYPES[0]}.csv" "$TEMP/Germany-${TYPES[1]}.csv" \
        | awk -F ' ' 'BEGIN { i=2;k=4 } { print (i "," k "," i%7 "," $1 "," $2 ) ; i=i+1 ; if ( i%7==0) {k=k+1}}' 
    ) > "Germany.csv"

}

function global_data {

(
cat <<EOF
USE COVID19;
DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS cases;

CREATE TABLE country ( cid BIGINT primary key, name CHAR(255), INDEX (name));
CREATE TABLE cases ( cid BIGINT , day DATE, count BIGINT, INDEX (cid, day));

EOF
cat "$TEMP/global-${DATA}.csv" \
| sed '1d; s#"\([^"]*\), *\([^"]*\)"#\2/\1#g;' \
| sed 's#^\([^,]*\),\([^,]*\),\([^,]*\),\([^,]*\),#-\n\2/\1\n#; s#\([^,]*\),#\1\n#g' \
| sed 's#/$##' \
| awk 'BEGIN {i=0;j=0;l=""} { if ($1=="-") { i=1;l="" } else { if (i==1) { l=$1;j=j+1; print("INSERT INTO country VALUES ( " j ",\"" $l "\");") } else { print("INSERT INTO cases VALUES (" j", ADDDATE(\"2020-01-21\"," i ")," $1 ");") }; i=i+1; } }'
) | mysql --user=rscript --password=rscript

}

pushd ${TARGET}

Download
US
Germany

popd
pushd ~/git/R-Example/COVID19

for r in *.r
do
	echo -e "--- $r ---"
	Rscript $r
done
popd

pushd ~/git/R-Example/RKI

for r in *.r
do
	echo -e "--- $r ---"
	Rscript $r
done
popd

