#!/bin/bash

DEBUG=OFF

# Color for output

red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`

function run_r {

    pushd "$HOME/git/R-Example/"

    pushd RKI
    for r in *.r
    do
        echo -e "\n\n${blue}+---------"
        echo -e "| ${red}${r}"
        echo -e "${blue}+---------${reset}\n\n"
        Rscript $r
#         read
#         reset
     done
    popd
popd
}

run_r
