#!/bin/bash

URL="https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile"
TEMP=$(mktemp -d)
#TEMP="/tmp/rki"
DEST="$TEMP/rki.xlsx"
CSV="$TEMP/rki"
SQL="$TEMP/rki.sql"
GIT="$HOME/git/R-Example/"

curl --output "$DEST" --url "$URL"

ssconvert  -S --export-type=Gnumeric_stf:stf_csv "$DEST" "${CSV}%n.csv"

# Create SQL import file 
# 1. Delete header rows
# 2. Replace invalid dates
# 3. Reformat dates
# 4. Create SQL statements

function bund  {

( cat <<EOF1
USE COVID19;
DROP TABLE IF EXISTS neu;

CREATE TABLE neu (date DATE primary key, cases INT, deaths INT);

SET autocommit=0;
# LOCK TABLE neu WRITE;

INSERT INTO neu VALUES ("2020-02-23",0,0);
EOF1

sed '1d; /^"/ s#^"25.08,2020",#2020-08-25,#; s#^\([0-9]\{2\}\).\([0-9]\{2\}\)\.\(202[0-9]\)#\3-\2-\1#; s#^\(202[0-9]\)/\([0-9]\{2\}\)/\([0-9]\{2\}\)#\1-\2-\3#;' "${CSV}1.csv" \
| sed 's#"[^"]*",##; s#,,#,0,#g; s#,,#,#g'   \
| awk -F ',' 'BEGIN {i=1}; {if ($2>0) print("INSERT INTO neu VALUES (ADDDATE(\"2020-02-23\"," i ")," $2 "," $5 ");" );i=i+1}'

cat <<EOF2
COMMIT;
UNLOCK TABLES;

CREATE TABLE IF NOT EXISTS rki (date DATE primary key, cases INT, deaths INT);

INSERT INTO rki 
SELECT neu.* 
FROM neu 
LEFT JOIN rki 
ON rki.date = neu.date
WHERE rki.date IS NULL;
COMMIT;
UNLOCK TABLES;
SELECT * FROM rki 
WHERE date > subdate(now(),10) ;
EOF2

) > "$SQL"

sudo rm /tmp/RKI_nach_{Tag,Kw}.csv 2>/dev/null

mysql --user=rscript --password=rscript < "$SQL"
mysql --user=rscript --password=rscript < "$HOME/git/R-Example/SQL/RKI_Export.sql"

sudo mv /tmp/RKI_nach* "$GIT/data/"
} # Ende Bund

function bundeslaender {

(
cat <<EOF3
USE COVID19 ;
DROP TABLE IF EXISTS rkibland;

CREATE TABLE rkibland (blid INT, name CHAR(32), INDEX (blid , name));
SET autocommit=0;
LOCK TABLE rkibland WRITE;
EOF3

cat "${TEMP}/rki2.csv" \
| sed '1d;$d; s#,.*##;' \
| awk -F ',' 'BEGIN {i=1;} { print ("INSERT INTO rkibland VALUES (" i ",\"" $1 "\");"); i=i+1}'

cat <<EOF4
COMMIT;
UNLOCK TABLES;
EOF4

cat <<EOF5
USE COVID19;
DROP TABLE IF EXISTS rkiblcases;

CREATE TABLE rkiblcases ( blid INT , reported DATE, cases INT, INDEX (blid, reported));

SET autocommit=0;
LOCK TABLE rkiblcases WRITE;
EOF5

cat "${TEMP}/rki2.csv" \
| sed '1d;$d; s#,*$##; s#^[^,]*,#-\n#; s#,#\n#g;' \
| awk -F ',' 'BEGIN {i=-1;j=0;} { if ($1=="-") { i=0; j=j+1; v=0} else { v=$1 };print("INSERT INTO rkiblcases VALUES (" j ", ADDDATE(\"2020-05-06\"," i ")," v ");") ; i=i+1; }'

cat <<EOF6
COMMIT;
UNLOCK TABLES;
EOF6
) > "$SQL"

mysql --user=rscript --password=rscript < "$SQL"

}

function run_r {
pushd $HOME/git/R-Example/

sudo mv /tmp/RKI_nach_{Tag,Kw}.csv data/

    pushd RKI
    for r in *.r
    do
        echo -e "--- $r ---"
        Rscript $r
     done
    popd
popd
}

bund
bundeslaender
run_r
