#!/bin/bash

DEBUG=OFF

# Color for output

red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`

# List of download URL

DASHURL="https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data"
DASHURL2="https://download.byggvir.de/RKI/RKI-COVID19.csv"

[ "$DEBUG" = "ON" ] && TEMP="/tmp/rki" || TEMP="/tmp/rki-$(date '+%F')"
[ ! -d  "${TEMP}" ] && mkdir "${TEMP}"

# echo -e "\n\n${blue}+---------"
# echo -e "| ${red}Tempoary file in: $TEMP"
# echo -e "${blue}+---------${reset}\n\n"

DASHDEST="$TEMP/RKI-COVID19.csv"
DASHDESTA="$TEMP/A-RKI-COVID19.csv"

function download {

# Download dashboard table

[ ! -e $DASHDEST ] && curl --output "$DASHDEST" --url "$DASHURL2"

[ ! -e $DASHDEST ] && curl --output "$DASHDESTA" --url "$DASHURL"

[ ! -e $DASHDEST ] && ( cat "$DASHDESTA" || curl --url "$DASHURL" ) \
| sed 's#"\([0-9]\{2\}\)\.\([0-9]\{2\}\)\.\([0-9]\{4\}\).*"#\3-\2-\1#g; s# 00:00:00##g; s#/#-#g; s#,[^,]*$##' \
| sed 's#LK Göttingen (alt)#LK Göttingen#' \
> "$DASHDEST"


}

function dashboard {

# Importieren der Zahlen aus der Tabelle für das RKI Dashboard

#     echo -e "\n\n${blue}+---------"
#     echo -e "| ${red}Importieren der Tabelle für das Dashboard RKI in die Datenbank"
#     echo -e "${blue}+---------${reset}\n\n" 

( cat <<EOF
USE COVID19;

DROP TABLE IF EXISTS RKIFaelle;

CREATE TABLE IF NOT EXISTS RKIFaelle (
    IdBundesland INT
    , Bundesland CHAR(32)
    , Landkreis CHAR(64)
    , Altersgruppe CHAR(7)
    , Geschlecht CHAR(1)
    , AnzahlFall INT
    , AnzahlTodesfall INT
    , ObjectId INT
    , Meldedatum DATE
    , IdLandkreis INT
    , Datenbestand DATE
    , NeuerFall INT 
    , NeuerTodesfall INT 
    , Refdatum DATE
    , NeuGenesen INT
    , AnzahlGenesen INT 
    , IstErkrankungsbeginn INT
    , PRIMARY KEY(ObjectId, Datenbestand));
    
ALTER TABLE RKIFaelle ADD INDEX(IdBundesland);
ALTER TABLE RKIFaelle ADD INDEX(IdLandkreis);
ALTER TABLE RKIFaelle ADD INDEX(Meldedatum);
ALTER TABLE RKIFaelle ADD INDEX(RefDatum);
ALTER TABLE RKIFaelle ADD INDEX(Geschlecht);
ALTER TABLE RKIFaelle ADD INDEX(Altersgruppe);

LOAD DATA LOCAL INFILE '$DASHDEST' 
    INTO TABLE RKIFaelle 
    FIELDS TERMINATED BY ',' 
    IGNORE 1 ROWS;

   
DROP TABLE IF EXISTS Bundesland;

CREATE TABLE Bundesland ( 
    IdBundesland INT PRIMARY KEY
    , Bundesland CHAR(32)
    , INDEX (Bundesland));
    
DROP TABLE IF EXISTS Landkreis;

CREATE TABLE Landkreis ( 
    IdLandkreis INT PRIMARY KEY
    , Landkreis CHAR(64)
    , INDEX (Landkreis));
    
INSERT INTO Bundesland
SELECT DISTINCT IdBundesland, Bundesland
FROM RKIFaelle;

INSERT INTO Landkreis
SELECT DISTINCT IdLandkreis, Landkreis
FROM RKIFaelle;

ALTER TABLE RKIFaelle DROP COLUMN Bundesland;
ALTER TABLE RKIFaelle DROP COLUMN Landkreis;

SELECT max(Meldedatum), max(Datenbestand) FROM RKIFaelle;  

EOF
) 
}

download
dashboard
