#!/bin/bash

# Import Sterbefälle nach Kw into MariaDB

cat <<EOF
USE COVID19;

DROP TABLE IF EXISTS SterbeFaelleKw;

CREATE TABLE IF NOT EXISTS SterbeFaelleKw (
    Year INT
  , CalWeek INT
  , AgeGroup INT
  , Sex INT
  , Count BIGINT
  , PRIMARY KEY (Year, CalWeek, AgeGroup, Sex)
  );
EOF

SEX=(M F)

for i in 0 1 
do 
    cat ~/git/R-Example/data/SterbeFälle${SEX[$i]}.csv \
    | sed '1d;s#,,#,0,#; s#,[^,]*$##; s#^\([0-9]*\),#A;\1\n#; s#,#\n#g' \
    | awk -F ';' 'BEGIN {AG=0;KW=0;} {if ($1 =="A" ) {KW=$2; AG=0} else { print("INSERT INTO SterbeFaelleKw values( 2020," KW "," AG*10 ",'$i'," $1 ");"); AG=AG+1}}'
done
