#!/bin/bash

URL="https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile"
TEMP=$(mktemp -d)
#TEMP="/tmp/rki"
DEST="$TEMP/rki.xlsx"
CSV="$TEMP/rki"
SQL="$TEMP/rki.sql"

curl --output "$DEST" --url "$URL"

ssconvert  -S --export-type=Gnumeric_stf:stf_csv "$DEST" "${CSV}%n.csv"

# Create SQL import file 
# 1. Delete header rows
# 2. Replace invalid dates
# 3. Reformat dates
# 4. Create SQL statements

( cat <<EOF
USE COVID19;
DROP TABLE IF EXISTS rki;
CREATE TABLE rki (day DATE primary key, cases BIGINT, deaths BIGINT);
INSERT INTO rki VALUES ("2020-02-25",0,0);
EOF
sed '1,3d; /^"/ s#^"25.08,2020",#2020-08-25,#; s#^\([0-9]\{2\}\).\([0-9]\{2\}\)\.\(202[0-9]\)#\3-\2-\1#; s#^\(202[0-9]\)/\([0-9]\{2\}\)/\([0-9]\{2\}\)#\1-\2-\3#;' "${CSV}1.csv" \
| sed 's#"[^"]*",##; s#,,#,0,#g; s#,,#,#g'   \
| awk -F ',' 'BEGIN {i=1}; {if ($2>0) print("INSERT INTO rki VALUES (ADDDATE(\"2020-02-25\"," i ")," $2 "," $5 ");" );i=i+1}'
) > "$SQL"

sudo rm /tmp/RKI_nach_{Tag,Kw}.csv 

mysql --user=rscript --password=rscript < "$SQL"

mysql --user=rscript --password=rscript < "../SQL/RKI_import.sql"

pushd $HOME/git/R-Example/data
sudo mv /tmp/RKI_nach_{Tag,Kw}.csv .
popd
