#!/bin/bash

LKDEST='/data/git/SARS-CoV-2_Infektionen_in_Deutschland/2020-06-30_Deutschland_Landkreise_GeoDemo.csv'

cat <<EOF | mysql --user=rscript --password=rscript
USE COVID19;
DROP TABLE IF EXISTS Landkreis;

CREATE TABLE Landkreis ( 
    IdLandkreis INT PRIMARY KEY
    , Landkreis CHAR(64)
    , Flaeche FLOAT
    , EW_insgesamt BIGINT
    , EW_maennlich BIGINT
    , EW_weiblich BIGINT
    , INDEX (Landkreis)
    , INDEX (Flaeche)
    , INDEX (EW_insgesamt));
    
LOAD DATA LOCAL INFILE '$LKDEST' 
    INTO TABLE Landkreis 
    FIELDS TERMINATED BY ',' 
    IGNORE 1 ROWS;

EOF
