#!/bin/bash

DEBUG=OFF
# Color for output

red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
reset=`tput sgr0`

CC=752     # SWE Country_Code 752

SEDDIR="$(dirname $0)/sed"
AWKDIR="$(dirname $0)/awk"

if [ -z "$1" ]
then
	DATE=$(date +%F --date="yesterday")
else 
	DATE="$1"
fi 

# List of download URL

[ "$DEBUG" = "ON" ] && TEMP="/tmp/rki" || TEMP="/tmp/rki-$(date '+%F')"
[ ! -d  "${TEMP}" ] && mkdir "${TEMP}"

FOHMURL="https://raw.githubusercontent.com/truthly/c19/master/files/$DATE.xlsx"
FOHMDEST="$TEMP/swe.xlsx"
FOHMCSV="$TEMP/swe"


echo -e "-- $DATE"

function download {

# Download table

[ ! -e "$FOHMDEST" ] && curl --output "$FOHMDEST" --url "$FOHMURL"

grep '404: Not Found' "$FOHMDEST"

if [ $? -ne 0 ] 
then
    ssconvert  -S --export-type=Gnumeric_stf:stf_csv "$FOHMDEST" "${FOHMCSV}%n.csv"
    return 0
else
    rm -f "$FOHMDEST"
    return 1
fi

}

function import {

    # SWE Country_Code 752

    ( echo 'CountryCode,Sex,Altersgruppe,Bis,Todesfall'
      sed --file "$SEDDIR/$CC.sed"  < "${FOHMCSV}5.csv" \
    | awk -F ',' -e 'BEGIN { CC='$CC';}' -f "$AWKDIR/$CC.awk"  
    ) > "../data/CoViD19Deaths/$CC.csv"
    
}

download
[ $? -eq 0 ] && import
