#!/bin/bash

# Download world population data from un.org

TEMP=$(mktemp -d)
TEMP="/tmp/un" ; [ ! -d  "${TEMP}" ] && mkdir "${TEMP}"
DEST="$TEMP/UN-population"
CSV="$TEMP/UN-population"
SUFFIX=".xlsx"

BASE="https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/EXCEL_FILES/1_Population/"
TABLES=("WPP2019_POP_F07_1_POPULATION_BY_AGE_BOTH_SEXES" \
    "WPP2019_POP_F07_2_POPULATION_BY_AGE_MALE"
    "WPP2019_POP_F07_3_POPULATION_BY_AGE_FEMALE" \
)
SEX=(both male female)
SSEX=(B M F)

#-- get data from un --

# for ((i=0;i<3;i++))
# do
#     curl --output "${DEST}-${SEX[${i}]}${SUFFIX}" \
#         --url "${BASE}${TABLES[${i}]}${SUFFIX}"
#     ssconvert  -S --export-type=Gnumeric_stf:stf_csv "${DEST}-${SEX[${i}]}${SUFFIX}" "${CSV}-${SEX[${i}]}-%n.csv"
# done
(
cat <<EOF
USE COVID19;

DROP TABLE IF EXISTS UNCountry;

DROP TABLE IF EXISTS UNPopulation;

DROP TABLE IF EXISTS UNAgegroups;

CREATE TABLE IF NOT EXISTS UNCountry ( CountryCode INT PRIMARY KEY, CountryArea CHAR(255), INDEX (CountryArea));

CREATE TABLE IF NOT EXISTS UNPopulation ( CountryCode INT, Year INT, Agegroup INT, Sex CHAR(1) , Count BIGINT
    , PRIMARY KEY (CountryCode, Year, Agegroup, Sex));

CREATE TABLE IF NOT EXISTS UNAgegroups ( id INT PRIMARY KEY AUTO_INCREMENT, Name CHAR(6));


EOF
grep 'Country/Area.*,2020,' "${DEST}-female-0.csv" \
| sed 's#"\([0-9]*\),\([0-9]*\)"#\1\2#g;s#"\([^,]*\), \([^"].*\)"#\1/\2#;s#"##g' \
| awk -F ','  '{print("INSERT INTO UNCountry VALUES (" $5 ",\"" $3 "\");")}' \
| sort -u \

sed '1,15d;17,$d;s#.*",##; s#\([^,]*\),*#INSERT INTO UNAgegroups VALUES ( NULL, "\1");\n#g' "${DEST}-both-0.csv"

for i in 1 2
do     
grep ',Country/Area,' "${DEST}-${SEX[$i]}-0.csv" \
| sed 's#"\([0-9]*\),\([0-9]*\)"#\1.\2#g;s#"\([^,]*\), \([^"].*\)"#\1/\2#;s#"##g' \
| sed 's#\([^,]*,\)\{4\}\([^,]*\),\(\([^,]*\),\)\{2\}#CountryCode\n\2\n#; s#,#\n#g;' \
| awk 'BEGIN { i=0 ; c="" ; y=0 } \
    { if ($1=="CountryCode") { i=1 } \
    else {if (i==1) { c=$1; i=i+1; } \
    else { if (i==2) { y=$1; i++ } \
    else { print("INSERT INTO UNPopulation VALUES (" c ", " y ", " i-2 ", \"'${SSEX[$i]}'\", " sprintf("%d" , $1*1000) ");" ); i=i+1 } } } }'
done

cat <<EOF
CREATE TABLE UN_JHU (CountryCode INT, cid INT, INDEX (CountryCode,cid))
SELECT U.CountryCode,J.cid FROM UNCountry AS U JOIN jhucountry AS J ON U.CountryArea = J.Country_Region;
EOF

) | mysql --user=rscript --password=rscript COVID19
